name: CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '**/*.html'
      - '**/*.css'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '**/*.html'
      - '**/*.css'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install --force

      - name: Run tests
        run: |
          npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Format code with Prettier
        run: |
          npm run format

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Formatted code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
